[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts = pre:scripts/build_identity.py
; Optimasi compiler untuk memori & kecepatan inferensi TinyML
build_flags = 
    -O3
    -mtext-section-literals
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    adafruit/DHT sensor library @ 1.4.7
    adafruit/Adafruit Unified Sensor @ 1.1.15
    mathworks/ThingSpeak @ 2.1.1
