[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Pengaturan build untuk optimasi memori & kecepatan inference TinyML
build_flags = 
    -O3
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mathworks/ThingSpeak @ ^2.0.0
