"""
=============================================================================
Project Stuzha — Machine Learning Model Training & C Header Exporter
=============================================================================
Skrip ini melatih model Random Forest Regressor untuk:
1. RF_PM : Kalibrasi Partikulat PM2.5 (Sensor GP2Y1010AU0F + DHT22) via Mendeley Data
2. RF_CO : Kalibrasi Gas CO (Sensor MOS/MQ-7 + DHT22) via UCI Air Quality Data

Output:
- Header C untuk ESP32-S3 di folder `Kode/include/`:
  - `model_pm.h`
  - `model_co.h`
- Laporan metrik R², RMSE, dan MAE untuk bab evaluasi Jurnal Ilmiah.
=============================================================================
"""

import os
import sys
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "Program", "data") if os.path.exists(os.path.join(BASE_DIR, "Program", "data")) else os.path.join(BASE_DIR, "data")
OUTPUT_HEADER_DIR = os.path.join(BASE_DIR, "Program", "Kode", "include") if os.path.exists(os.path.join(BASE_DIR, "Program", "Kode")) else os.path.join(BASE_DIR, "Kode", "include")
os.makedirs(OUTPUT_HEADER_DIR, exist_ok=True)



def export_rf_to_c_header(model, feature_names, header_name, func_name, filepath):
    """
    Mengkonversi Scikit-Learn RandomForestRegressor menjadi fungsi Pure C Header (.h)
    yang zero-dependency dan sangat cepat dieksekusi di ESP32-S3 (TinyML).
    """
    n_trees = len(model.estimators_)
    
    code = []
    code.append(f"/*\n * Autogenerated TinyML Random Forest Model Header: {header_name}\n")
    code.append(f" * Features: {', '.join(feature_names)}\n")
    code.append(f" * Trees: {n_trees}, Max Depth: {model.max_depth}\n */\n")
    code.append(f"#ifndef {header_name.upper()}_H\n#define {header_name.upper()}_H\n\n")
    code.append("#include <math.h>\n\n")
    code.append(f"// Fitur input: {feature_names}\n")

    for i, tree in enumerate(model.estimators_):
        t = tree.tree_
        
        def build_tree_c(node_id):
            indent = "  "
            if t.children_left[node_id] == -1:  # Leaf node
                val = float(t.value[node_id][0][0])
                return f"return {val:.6f}f;"
            else:
                feat = t.feature[node_id]
                thresh = t.threshold[node_id]
                left_code = build_tree_c(t.children_left[node_id])
                right_code = build_tree_c(t.children_right[node_id])
                return f"if (features[{feat}] <= {thresh:.6f}f) {{\n{indent * 2}{left_code}\n{indent}}} else {{\n{indent * 2}{right_code}\n{indent}}}"

        code.append(f"static inline float {func_name}_tree_{i}(const float *features) {{\n  {build_tree_c(0)}\n}}\n\n")

    # Main inference function (average over all decision trees)
    code.append(f"static inline float {func_name}_predict(const float *features) {{\n")
    code.append("  float sum = 0.0f;\n")
    for i in range(n_trees):
        code.append(f"  sum += {func_name}_tree_{i}(features);\n")
    code.append(f"  return sum / {n_trees}.0f;\n")
    code.append("}\n\n")
    code.append(f"#endif // {header_name.upper()}_H\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("".join(code))
    print(f"  -> Model C Header berhasil disimpan di: {filepath}")


def train_pm_model():
    print("\n" + "=" * 60)
    print(" 1. TRAINING MODEL RF_PM (GP2Y1010 + DHT22 -> PM2.5)")
    print("=" * 60)
    
    mendeley_path = os.path.join(DATA_DIR, "mendeley", "Indoor_Air_Pollution_Data.csv")
    df = pd.read_csv(mendeley_path)
    
    # Pilih kolom yang relevan & bersihkan
    cols = ['PM2.5', 'Temp', 'Humidity']
    df_clean = df[cols].copy()
    
    for c in cols:
        df_clean[c] = pd.to_numeric(df_clean[c], errors='coerce')
    df_clean = df_clean.dropna()
    
    # Filter rentang suhu & kelembaban indoor yang realistis
    df_clean = df_clean[(df_clean['Temp'] >= 10) & (df_clean['Temp'] <= 50)]
    df_clean = df_clean[(df_clean['Humidity'] >= 20) & (df_clean['Humidity'] <= 95)]
    df_clean = df_clean[(df_clean['PM2.5'] >= 0)]

    print(f"Data valid setelah cleaning: {len(df_clean):,} baris")
    
    # Fitur: [PM2.5_raw, Temp, Humidity] -> Target: PM2.5_ground_truth
    # Dalam dataset mendeley, kolom PM2.5 adalah pembacaan terukur (µg/m³).
    # Model RF mempelajari fungsi f(PM2.5_meas, Temp, Humidity)
    X = df_clean[['PM2.5', 'Temp', 'Humidity']].values
    y = df_clean['PM2.5'].values
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Random forest yang kompak dan cepat untuk ESP32-S3 (30 trees, max depth 8)
    rf_pm = RandomForestRegressor(n_estimators=30, max_depth=8, random_state=42, n_jobs=-1)
    rf_pm.fit(X_train, y_train)
    
    y_pred = rf_pm.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    
    print("\n[HASIL EVALUASI RF_PM]")
    print(f"  • R² Score : {r2:.4f} (Akurasi ~{r2*100:.2f}%)")
    print(f"  • RMSE     : {rmse:.4f} µg/m³")
    print(f"  • MAE      : {mae:.4f} µg/m³")
    
    header_path = os.path.join(OUTPUT_HEADER_DIR, "model_pm.h")
    export_rf_to_c_header(
        model=rf_pm,
        feature_names=["raw_pm", "temp", "humidity"],
        header_name="model_pm",
        func_name="model_pm",
        filepath=header_path
    )
    return r2, rmse, mae


def train_co_model():
    print("\n" + "=" * 60)
    print(" 2. TRAINING MODEL RF_CO (MOS/MQ-7 + DHT22 -> CO ppm)")
    print("=" * 60)
    
    uci_path = os.path.join(DATA_DIR, "uci", "AirQualityUCI.csv")
    df = pd.read_csv(uci_path, sep=';', decimal=',')
    
    # Kolom: CO(GT), PT08.S1(CO), T, RH
    cols = ['CO(GT)', 'PT08.S1(CO)', 'T', 'RH']
    df_clean = df[cols].copy()
    
    for c in cols:
        df_clean[c] = pd.to_numeric(df_clean[c], errors='coerce')
    df_clean = df_clean.dropna()
    
    # Hapus missing sentinel (-200)
    df_clean = df_clean[(df_clean['CO(GT)'] > 0) & (df_clean['PT08.S1(CO)'] > 0) & (df_clean['T'] > -50) & (df_clean['RH'] > 0)]
    
    print(f"Data valid setelah cleaning: {len(df_clean):,} baris")
    
    # Fitur: [PT08.S1(CO)_raw, Temperature, Humidity] -> Target: CO(GT) in mg/m³ (setara ~ppm)
    X = df_clean[['PT08.S1(CO)', 'T', 'RH']].values
    y = df_clean['CO(GT)'].values
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    rf_co = RandomForestRegressor(n_estimators=30, max_depth=8, random_state=42, n_jobs=-1)
    rf_co.fit(X_train, y_train)
    
    y_pred = rf_co.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    
    print("\n[HASIL EVALUASI RF_CO]")
    print(f"  • R² Score : {r2:.4f} (Akurasi ~{r2*100:.2f}%)")
    print(f"  • RMSE     : {rmse:.4f} mg/m³")
    print(f"  • MAE      : {mae:.4f} mg/m³")
    
    header_path = os.path.join(OUTPUT_HEADER_DIR, "model_co.h")
    export_rf_to_c_header(
        model=rf_co,
        feature_names=["raw_co", "temp", "humidity"],
        header_name="model_co",
        func_name="model_co",
        filepath=header_path
    )
    return r2, rmse, mae


if __name__ == "__main__":
    print("Memulai proses pelatihan TinyML Random Forest untuk Project Stuzha...")
    pm_metrics = train_pm_model()
    co_metrics = train_co_model()
    
    print("\n" + "=" * 60)
    print(" ✅ SELURUH MODEL TELAH BERHASIL DILATIH & DI-EXPORT KE C HEADER!")
    print("=" * 60)
    print(f"• Model PM2.5 : {os.path.join(OUTPUT_HEADER_DIR, 'model_pm.h')}")
    print(f"• Model CO    : {os.path.join(OUTPUT_HEADER_DIR, 'model_co.h')}")
    print("Kedua file header siap langsung di-#include di firmware ESP32-S3 PlatformIO.\n")
