"""
=============================================================================
Project Stuzha — Machine Learning Model Training & C Header Exporter (v2.1)
=============================================================================
Revisi Ilmiah (Berdasarkan Peer Review):
1. Mengeliminasi TARGET LEAKAGE pada PM2.5.
   - Dataset Mendeley (mg/m³) dikonversi ke µg/m³ (Ground Truth).
   - Fitur input disimulasikan sebagai PM_raw yang terdistorsi oleh RH
     (mengikuti model pertumbuhan higroskopis aerosol / Hanel-Kohler equation
     sesuai Jurnal 4, 6, dan Adong et al. 2022).
   - Skala fitur input PM_raw di model C sekarang IDENTIK dengan output rumus
     datasheet GP2Y di ESP32: PM_raw = (0.17 * V - 0.1) * 1000 µg/m³.
2. Menyelaraskan Skala Sensor Gas CO (MQ-7):
   - Menggunakan normalisasi rasio resistansi (Rs/R0) sensor MOS dari UCI.
   - ESP32 menghitung rasio Rs/R0 yang matched dengan skala model.
=============================================================================
"""

import os
import sys
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "Program", "data") if os.path.exists(os.path.join(BASE_DIR, "Program", "data")) else os.path.join(BASE_DIR, "data")
OUTPUT_HEADER_DIR = os.path.join(BASE_DIR, "Program", "Kode", "include") if os.path.exists(os.path.join(BASE_DIR, "Program", "Kode")) else os.path.join(BASE_DIR, "Kode", "include")
os.makedirs(OUTPUT_HEADER_DIR, exist_ok=True)


def export_rf_to_c_header(model, feature_names, header_name, func_name, filepath):
    """
    Mengkonversi Scikit-Learn RandomForestRegressor menjadi fungsi Pure C Header (.h)
    yang zero-dependency dan sangat cepat dieksekusi di ESP32-S3 (TinyML).
    """
    n_trees = len(model.estimators_)
    
    code = []
    code.append(f"/*\n * Autogenerated TinyML Random Forest Model Header: {header_name}\n")
    code.append(f" * Features: {', '.join(feature_names)}\n")
    code.append(f" * Trees: {n_trees}, Max Depth: {model.max_depth}\n */\n")
    code.append(f"#ifndef {header_name.upper()}_H\n#define {header_name.upper()}_H\n\n")
    code.append("#include <math.h>\n\n")

    for i, tree in enumerate(model.estimators_):
        t = tree.tree_
        
        def build_tree_c(node_id):
            indent = "  "
            if t.children_left[node_id] == -1:  # Leaf node
                val = float(t.value[node_id][0][0])
                return f"return {val:.4f}f;"
            else:
                feat = t.feature[node_id]
                thresh = t.threshold[node_id]
                left_code = build_tree_c(t.children_left[node_id])
                right_code = build_tree_c(t.children_right[node_id])
                return f"if (features[{feat}] <= {thresh:.4f}f) {{\n{indent * 2}{left_code}\n{indent}}} else {{\n{indent * 2}{right_code}\n{indent}}}"

        code.append(f"static inline float {func_name}_tree_{i}(const float *features) {{\n  {build_tree_c(0)}\n}}\n\n")

    # Main inference function (rata-rata semua decision trees)
    code.append(f"static inline float {func_name}_predict(const float *features) {{\n")
    code.append("  float sum = 0.0f;\n")
    for i in range(n_trees):
        code.append(f"  sum += {func_name}_tree_{i}(features);\n")
    code.append(f"  return sum / {n_trees}.0f;\n")
    code.append("}\n\n")
    code.append(f"#endif // {header_name.upper()}_H\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("".join(code))
    print(f"  -> Model C Header berhasil disimpan di: {filepath}")


def train_pm_model():
    print("\n" + "=" * 65)
    print(" 1. TRAINING MODEL RF_PM (GP2Y1010 + DHT22 -> PM2.5 µg/m³)")
    print("    Bebas Target Leakage & Skala Matched dengan ADC ESP32")
    print("=" * 65)
    
    mendeley_path = os.path.join(DATA_DIR, "mendeley", "Indoor_Air_Pollution_Data.csv")
    df = pd.read_csv(mendeley_path, low_memory=False)
    
    cols = ['PM2.5', 'Temp', 'Humidity']
    df_clean = df[cols].copy()
    
    for c in cols:
        df_clean[c] = pd.to_numeric(df_clean[c], errors='coerce')
    df_clean = df_clean.dropna()
    
    # Filter rentang fisik yang masuk akal
    df_clean = df_clean[(df_clean['Temp'] >= 15) & (df_clean['Temp'] <= 45)]
    df_clean = df_clean[(df_clean['Humidity'] >= 20) & (df_clean['Humidity'] <= 90)]
    df_clean = df_clean[(df_clean['PM2.5'] > 0)]

    print(f"Data valid dari Mendeley: {len(df_clean):,} baris")

    # Ground Truth sebenarnya (µg/m³): Nilai kolom Mendeley (mg/m³) dikalikan 1000
    # Contoh: 0.05 mg/m³ -> 50 µg/m³; 0.15 mg/m³ -> 150 µg/m³
    pm_true_ug = df_clean['PM2.5'].values * 1000.0
    temp = df_clean['Temp'].values
    rh = df_clean['Humidity'].values

    # SIMULASI FISIK SENSOR OPTIK (Adong et al. 2022 / Hanel Aerosol Growth):
    # Sensor debu optik GP2Y membaca hamburan cahaya yang membesar saat RH tinggi
    # f(RH) = 1 + gamma * (RH / 100)^2
    np.random.seed(42)
    gamma = 0.65  # Koefisien pembiasan uap air tipikal partikulat indoor
    hygroscopic_factor = 1.0 + gamma * ((rh / 100.0) ** 2)
    
    # Tambahkan noise sensor murah (+- 5% Gaussian noise)
    noise = np.random.normal(1.0, 0.05, size=len(pm_true_ug))
    
    # Ini adalah nilai PM_raw yang dibaca sensor GP2Y sebelum kalibrasi (dalam µg/m³)
    pm_raw_ug = pm_true_ug * hygroscopic_factor * noise

    # Input Fitur: [PM_raw (µg/m³), Suhu (°C), Kelembapan (%)]
    X = np.column_stack((pm_raw_ug, temp, rh))
    # Target: PM_true terkalibrasi murni (µg/m³)
    y = pm_true_ug

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Latih Random Forest (30 trees, depth 8 agar ringan di ESP32)
    rf_pm = RandomForestRegressor(n_estimators=30, max_depth=8, random_state=42, n_jobs=-1)
    rf_pm.fit(X_train, y_train)

    y_pred = rf_pm.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    print("\n[HASIL EVALUASI MODEL RF_PM (VALID & BEBAS TARGET LEAKAGE)]")
    print(f"  • R² Score : {r2:.4f} (Akurasi Kalibrasi: ~{r2*100:.2f}%)")
    print(f"  • RMSE     : {rmse:.2f} µg/m³")
    print(f"  • MAE      : {mae:.2f} µg/m³")

    header_path = os.path.join(OUTPUT_HEADER_DIR, "model_pm.h")
    export_rf_to_c_header(
        model=rf_pm,
        feature_names=["pm_raw_ug", "temp", "humidity"],
        header_name="model_pm",
        func_name="model_pm",
        filepath=header_path
    )
    return r2, rmse, mae


def train_co_model():
    print("\n" + "=" * 65)
    print(" 2. TRAINING MODEL RF_CO (MOS/MQ-7 Rs/R0 + DHT22 -> CO ppm)")
    print("    Skala Rasio Resistansi Matched dengan ESP32")
    print("=" * 65)
    
    uci_path = os.path.join(DATA_DIR, "uci", "AirQualityUCI.csv")
    df = pd.read_csv(uci_path, sep=';', decimal=',')
    
    cols = ['CO(GT)', 'PT08.S1(CO)', 'T', 'RH']
    df_clean = df[cols].copy()
    
    for c in cols:
        df_clean[c] = pd.to_numeric(df_clean[c], errors='coerce')
    df_clean = df_clean.dropna()
    
    # Hapus missing sentinel (-200)
    df_clean = df_clean[(df_clean['CO(GT)'] > 0) & (df_clean['PT08.S1(CO)'] > 0) & (df_clean['T'] > -10) & (df_clean['RH'] > 0)]
    
    print(f"Data valid dari UCI: {len(df_clean):,} baris")

    # Normalisasi resistansi sensor MOS ke rasio Rs/R0
    # PT08.S1 baseline udara bersih (R0) ~ 1000 Ohm
    r0_baseline = np.percentile(df_clean['PT08.S1(CO)'], 10)  # R0 di udara relatif bersih
    rs_r0_ratio = df_clean['PT08.S1(CO)'].values / r0_baseline
    
    temp = df_clean['T'].values
    rh = df_clean['RH'].values
    co_gt = df_clean['CO(GT)'].values  # mg/m³ (mendekati ppm untuk CO ambient)

    # Fitur: [Rs/R0 ratio, Temperature, Humidity] -> Target: CO(GT)
    X = np.column_stack((rs_r0_ratio, temp, rh))
    y = co_gt

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    rf_co = RandomForestRegressor(n_estimators=30, max_depth=8, random_state=42, n_jobs=-1)
    rf_co.fit(X_train, y_train)

    y_pred = rf_co.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    print("\n[HASIL EVALUASI MODEL RF_CO (TERNORMALISASI)]")
    print(f"  • R² Score : {r2:.4f} (Akurasi: ~{r2*100:.2f}%)")
    print(f"  • RMSE     : {rmse:.2f} mg/m³ (~ppm)")
    print(f"  • MAE      : {mae:.2f} mg/m³ (~ppm)")

    header_path = os.path.join(OUTPUT_HEADER_DIR, "model_co.h")
    export_rf_to_c_header(
        model=rf_co,
        feature_names=["rs_r0_ratio", "temp", "humidity"],
        header_name="model_co",
        func_name="model_co",
        filepath=header_path
    )
    return r2, rmse, mae


if __name__ == "__main__":
    print("Memulai proses pelatihan TinyML Random Forest v2.1 (Scientific Revision)...")
    pm_metrics = train_pm_model()
    co_metrics = train_co_model()
    
    print("\n" + "=" * 65)
    print(" ✅ SELURUH MODEL TELAH DIREVISI & DI-EXPORT KE C HEADER!")
    print("=" * 65)
    print(f"• Model PM2.5 : {os.path.join(OUTPUT_HEADER_DIR, 'model_pm.h')}")
    print(f"• Model CO    : {os.path.join(OUTPUT_HEADER_DIR, 'model_co.h')}")
    print("Kedua file header sekarang 100% matched dengan formula firmware ESP32-S3.\n")
